import { FALLBACK_LANGUAGE, isAppLanguage, type AppLanguage } from '../i18n/languages';

const english = {
  coverage: 'Research coverage: {completed}/{total}; completed: {repositories}.',
  none: 'none',
  pending: 'Pending batch {batch} (total research deadline reached): {repositories}',
  noEvidence: 'No repository evidence retrieved in this turn.',
  researchTimeout: 'Research deadline reached; no completed evidence result was returned.',
  synthesisTimeout: 'Synthesis deadline reached; completed per-repository research is retained below.',
  citationsRemoved: 'Unverified citations were removed; the remaining research is retained.',
  sources: 'Sources',
  unavailableConfig: 'The selected AI configuration is unavailable. Check its credentials or enable the local CLI.',
} as const;

type WorkbenchTextKey = keyof typeof english;
const translations: Record<AppLanguage, Record<WorkbenchTextKey, string>> = {
  en: english,
  zh: {
    coverage: '研究覆盖：{completed}/{total}；已完成：{repositories}。',
    none: '无',
    pending: '待研究批次 {batch}（总研究时间预算已用尽）：{repositories}',
    noEvidence: '本轮未获得仓库证据。',
    researchTimeout: '研究时间预算已用尽；未返回完整的证据结果。',
    synthesisTimeout: '汇总时间预算已用尽；以下保留已完成的逐仓库研究结果。',
    citationsRemoved: '已移除无法核验的引用；其余研究内容已保留。',
    sources: '来源',
    unavailableConfig: '所选 AI 配置不可用。请检查凭据或启用本地 CLI。',
  },
  'zh-TW': {
    coverage: '研究涵蓋：{completed}/{total}；已完成：{repositories}。',
    none: '無',
    pending: '待研究批次 {batch}（總研究時間預算已用盡）：{repositories}',
    noEvidence: '本輪未取得儲存庫證據。',
    researchTimeout: '研究時間預算已用盡；未傳回完整的證據結果。',
    synthesisTimeout: '彙整時間預算已用盡；以下保留已完成的各儲存庫研究結果。',
    citationsRemoved: '已移除無法核驗的引用；其餘研究內容已保留。',
    sources: '來源',
    unavailableConfig: '所選 AI 設定無法使用。請檢查憑證或啟用本機 CLI。',
  },
  fr: {
    coverage: 'Couverture de recherche : {completed}/{total} ; terminés : {repositories}.',
    none: 'aucun',
    pending: 'Lot en attente {batch} (délai total de recherche atteint) : {repositories}',
    noEvidence: 'Aucune preuve du dépôt récupérée pendant ce tour.',
    researchTimeout: 'Délai de recherche atteint ; aucun résultat complet avec preuves n’a été renvoyé.',
    synthesisTimeout: 'Délai de synthèse atteint ; les recherches terminées par dépôt sont conservées ci-dessous.',
    citationsRemoved: 'Les citations non vérifiables ont été supprimées ; le reste de la recherche est conservé.',
    sources: 'Sources',
    unavailableConfig: 'La configuration IA sélectionnée est indisponible. Vérifiez ses identifiants ou activez la CLI locale.',
  },
  de: {
    coverage: 'Rechercheabdeckung: {completed}/{total}; abgeschlossen: {repositories}.',
    none: 'keine',
    pending: 'Ausstehende Gruppe {batch} (gesamtes Recherchezeitlimit erreicht): {repositories}',
    noEvidence: 'In diesem Durchlauf wurden keine Repository-Belege abgerufen.',
    researchTimeout: 'Recherchezeitlimit erreicht; kein vollständiges Ergebnis mit Belegen zurückgegeben.',
    synthesisTimeout: 'Zeitlimit für die Zusammenfassung erreicht; abgeschlossene Repository-Recherchen bleiben unten erhalten.',
    citationsRemoved: 'Nicht überprüfbare Quellenangaben wurden entfernt; die übrige Recherche bleibt erhalten.',
    sources: 'Quellen',
    unavailableConfig: 'Die gewählte KI-Konfiguration ist nicht verfügbar. Prüfen Sie die Zugangsdaten oder aktivieren Sie die lokale CLI.',
  },
  es: {
    coverage: 'Cobertura de investigación: {completed}/{total}; completados: {repositories}.',
    none: 'ninguno',
    pending: 'Lote pendiente {batch} (plazo total de investigación agotado): {repositories}',
    noEvidence: 'No se obtuvieron pruebas del repositorio en este turno.',
    researchTimeout: 'Plazo de investigación agotado; no se devolvió un resultado completo con pruebas.',
    synthesisTimeout: 'Plazo de síntesis agotado; las investigaciones completadas por repositorio se conservan a continuación.',
    citationsRemoved: 'Se eliminaron las citas no verificables; se conserva el resto de la investigación.',
    sources: 'Fuentes',
    unavailableConfig: 'La configuración de IA seleccionada no está disponible. Compruebe las credenciales o active la CLI local.',
  },
  'pt-BR': {
    coverage: 'Cobertura da pesquisa: {completed}/{total}; concluídos: {repositories}.',
    none: 'nenhum',
    pending: 'Lote pendente {batch} (prazo total da pesquisa esgotado): {repositories}',
    noEvidence: 'Nenhuma evidência do repositório foi obtida nesta rodada.',
    researchTimeout: 'Prazo da pesquisa esgotado; nenhum resultado completo com evidências foi retornado.',
    synthesisTimeout: 'Prazo da síntese esgotado; as pesquisas concluídas por repositório estão preservadas abaixo.',
    citationsRemoved: 'Citações não verificáveis foram removidas; o restante da pesquisa foi preservado.',
    sources: 'Fontes',
    unavailableConfig: 'A configuração de IA selecionada está indisponível. Verifique as credenciais ou ative a CLI local.',
  },
  ru: {
    coverage: 'Охват исследования: {completed}/{total}; завершены: {repositories}.',
    none: 'нет',
    pending: 'Ожидающая группа {batch} (общее время исследования истекло): {repositories}',
    noEvidence: 'За этот проход не получено подтверждающих данных из репозитория.',
    researchTimeout: 'Время исследования истекло; полный результат с подтверждающими данными не получен.',
    synthesisTimeout: 'Время на обобщение истекло; завершённые исследования репозиториев сохранены ниже.',
    citationsRemoved: 'Непроверяемые ссылки удалены; остальная часть исследования сохранена.',
    sources: 'Источники',
    unavailableConfig: 'Выбранная конфигурация ИИ недоступна. Проверьте учётные данные или включите локальный CLI.',
  },
  ja: {
    coverage: '調査範囲：{completed}/{total}；完了：{repositories}。',
    none: 'なし',
    pending: '未調査バッチ {batch}（調査全体の制限時間に到達）：{repositories}',
    noEvidence: '今回の調査ではリポジトリの根拠を取得できませんでした。',
    researchTimeout: '調査の制限時間に到達し、根拠を含む完全な結果は返されませんでした。',
    synthesisTimeout: '統合の制限時間に到達しました。完了した各リポジトリの調査結果を以下に保持しています。',
    citationsRemoved: '検証できない引用を削除し、残りの調査内容を保持しました。',
    sources: '出典',
    unavailableConfig: '選択した AI 設定は利用できません。認証情報を確認するか、ローカル CLI を有効にしてください。',
  },
  ko: {
    coverage: '조사 범위: {completed}/{total}; 완료: {repositories}.',
    none: '없음',
    pending: '대기 중인 묶음 {batch} (전체 조사 시간 한도 도달): {repositories}',
    noEvidence: '이번 조사에서 저장소 근거를 가져오지 못했습니다.',
    researchTimeout: '조사 시간 한도에 도달하여 근거가 포함된 완전한 결과를 받지 못했습니다.',
    synthesisTimeout: '종합 시간 한도에 도달했습니다. 완료된 저장소별 조사 결과는 아래에 보존됩니다.',
    citationsRemoved: '검증할 수 없는 인용을 제거하고 나머지 조사 내용은 보존했습니다.',
    sources: '출처',
    unavailableConfig: '선택한 AI 설정을 사용할 수 없습니다. 인증 정보를 확인하거나 로컬 CLI를 활성화하세요.',
  },
};

export const workbenchText = (
  language: string,
  key: WorkbenchTextKey,
  values: Record<string, string | number> = {},
): string => translations[isAppLanguage(language) ? language : FALLBACK_LANGUAGE][key]
  .replace(/\{(\w+)\}/g, (placeholder, name: string) => String(values[name] ?? placeholder));
