const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');
const {createHtmlReadingService,beijingDay,beijingMinute}=require('./htmlReading');
function fixture(t,sendMail=async()=>({accepted:['reader@gmail.com']})) {
  const root=fs.mkdtempSync(path.join(os.tmpdir(),'gsm-html-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));let clock=new Date('2026-09-30T00:00:00Z');let sent=[];
  const opts={fs,path,userData:root,safeStorage:{isEncryptionAvailable:()=>true,encryptString:text=>Buffer.from('encrypted:'+Buffer.from(text).toString('base64')),decryptString:buf=>Buffer.from(buf.toString().slice(10),'base64').toString()},createTransport:options=>({verify:async()=>true,sendMail:async value=>{sent.push({options,value});return sendMail(value);},close:()=>{}}),now:()=>clock};
  const service=createHtmlReadingService(opts);service.saveCredential({accountId:'42',from:'sender@gmail.com',to:'reader@gmail.com',password:'abcdefghijklmnop'});return{service,root,opts,sent,setTime:value=>{clock=new Date(value);}};
}
test('Beijing schedule does not use host timezone',()=>{assert.equal(beijingDay(new Date('2026-09-29T20:00:00Z')),'2026-09-30');assert.equal(beijingMinute(new Date('2026-09-30T00:00:00Z')),'08:00');});
test('credential persistence is encrypted and status omits the password',t=>{const f=fixture(t);assert.ok(!fs.readFileSync(path.join(f.root,'html-reading/gmail.enc'),'utf8').includes('abcdefghijklmnop'));assert.ok(!JSON.stringify(f.service.status()).includes('abcdefghijklmnop'));});
test('schedule runs once per Beijing day and survives restart',t=>{const f=fixture(t);f.service.configure({accountId:'42',enabled:true,time:'08:00'});f.setTime('2026-09-29T23:59:00Z');assert.equal(f.service.due(),null);f.setTime('2026-09-30T00:00:00Z');const due=f.service.due();assert.equal(due.accountId,'42');assert.equal(f.service.due(),null);f.service.generationFailed(due.requestId,'failed');assert.equal(f.service.due(),null);assert.equal(createHtmlReadingService(f.opts).due(),null);f.setTime('2026-10-01T00:00:00Z');assert.ok(f.service.due());});
test('SMTP uses authenticated TLS and an actual HTML attachment',async t=>{const f=fixture(t);const result=await f.service.send({accountId:'42',html:'<!doctype html><p>GSM</p>',snapshotId:'snapshot'});assert.equal(result.success,true);assert.equal(f.sent[0].options.secure,true);assert.equal(f.sent[0].options.port,465);assert.equal(f.sent[0].value.attachments[0].content,'<!doctype html><p>GSM</p>');assert.equal(f.sent[0].value.disableFileAccess,true);});
test('uncertain send is recorded and never automatically repeated',async t=>{const f=fixture(t,async()=>{throw Object.assign(Error('secret transport details'),{code:'ETIMEDOUT'});});f.service.configure({accountId:'42',enabled:true,time:'08:00'});const due=f.service.due();const result=await f.service.send({accountId:'42',requestId:due.requestId,html:'<!doctype html>',snapshotId:'snapshot'});assert.equal(result.status,'unconfirmed');assert.equal(f.service.due(),null);assert.ok(!JSON.stringify(f.service.status()).includes('secret transport details'));});
test('old account, stale task, traversal and unavailable safe storage are rejected',async t=>{const f=fixture(t);await assert.rejects(f.service.send({accountId:'43',html:'<!doctype html>',snapshotId:'snapshot'}));await assert.rejects(f.service.send({accountId:'42',requestId:'stale',html:'<!doctype html>',snapshotId:'snapshot'}));await assert.rejects(f.service.send({accountId:'42',html:'<!doctype html>',snapshotId:'../bad'}));const opts={...f.opts,safeStorage:{isEncryptionAvailable:()=>false}};assert.throws(()=>createHtmlReadingService(opts).saveCredential({accountId:'42',from:'a@gmail.com',to:'b@gmail.com',password:'abcdefghijklmnop'}));});
test('switching account invalidates a generating task',async t=>{const f=fixture(t);f.service.configure({accountId:'42',enabled:true,time:'08:00'});const due=f.service.due();f.service.configure(null);await assert.rejects(f.service.send({accountId:'42',requestId:due.requestId,html:'<!doctype html>',snapshotId:'snapshot'}));assert.equal(f.service.status().busy,false);});
test('a generating timeout cannot free verification or an active SMTP send',async t=>{let resolve;const f=fixture(t,()=>new Promise(r=>{resolve=r;}));f.service.configure({accountId:'42',enabled:true,time:'08:00'});const due=f.service.due();const sending=f.service.send({accountId:'42',requestId:due.requestId,html:'<!doctype html>',snapshotId:'snapshot'});f.service.generationFailed(due.requestId,'late timer');assert.equal(f.service.status().busy,true);await Promise.resolve();f.service.generationFailed(due.requestId,'late timer');assert.equal(f.service.status().busy,true);resolve({accepted:['reader@gmail.com']});await sending;});
test('duplicate scheduled delivery cannot submit a second SMTP request',async t=>{let resolve;const f=fixture(t,()=>new Promise(r=>{resolve=r;}));f.service.configure({accountId:'42',enabled:true,time:'08:00'});const due=f.service.due();const payload={accountId:'42',requestId:due.requestId,html:'<!doctype html>',snapshotId:'snapshot'};const sending=f.service.send(payload);await assert.rejects(f.service.send(payload));assert.equal(f.sent.length,1);resolve({accepted:['reader@gmail.com']});await sending;await assert.rejects(f.service.send(payload));});
