import 'fake-indexeddb/auto';
import { act, renderHook, waitFor } from '@testing-library/react';
import { describe, expect, it, vi } from 'vitest';
import { HomeDatabase } from './database';
import type { HomeSync } from './sync';
import type { HomeRecord } from './types';
const mocks = vi.hoisted(() => ({ sync: null as HomeSync | null, listeners: new Set<() => void>() }));
vi.mock('./desktop', () => ({ getDesktopHomeSync: () => mocks.sync, subscribeDesktopHome: (listener: () => void) => { mocks.listeners.add(listener); return () => mocks.listeners.delete(listener); } }));
import { useDiscoveryPostRead } from './useDiscoveryPostRead';

describe('desktop source post read bridge', () => {
  it('ignores failed writes from a closed modal after reopening the same post', async () => {
    const db = new HomeDatabase(crypto.randomUUID());
    mocks.sync = { db, changed: vi.fn() } as unknown as HomeSync;
    const hook = renderHook(({ enabled }) => useDiscoveryPostRead('telegram', 'same', enabled), { initialProps: { enabled: true } });
    await waitFor(() => expect(hook.result.current.available).toBe(true));
    let reject!: (reason: Error) => void;
    vi.spyOn(db, 'edit').mockImplementationOnce(() => new Promise<void>((_, fail) => { reject = fail; }));
    let pending!: Promise<void>;
    act(() => { pending = hook.result.current.mark(true); });
    hook.rerender({ enabled: false });
    expect(hook.result.current.available).toBe(false);
    hook.rerender({ enabled: true });
    await waitFor(() => expect(hook.result.current.available).toBe(true));
    await act(async () => { reject(new Error('old failure')); await pending; });
    expect(hook.result.current.error).toBe('');
    expect(hook.result.current.busy).toBe(false);
    hook.unmount();
  });
  it('ignores a late read from the previous post and refuses writes until the new read is ready', async () => {
    const db = new HomeDatabase(crypto.randomUUID());
    mocks.sync = { db, changed: vi.fn() } as unknown as HomeSync;
    let resolve!: (record: HomeRecord) => void;
    vi.spyOn(db, 'getRecord').mockImplementationOnce(() => new Promise<HomeRecord>(done => { resolve = done; }));
    const edit = vi.spyOn(db, 'edit');
    const hook = renderHook(({ id }) => useDiscoveryPostRead('telegram', id, true), { initialProps: { id: 'old' } });
    await act(() => hook.result.current.mark(true));
    expect(edit).not.toHaveBeenCalled();
    hook.rerender({ id: 'new' });
    await waitFor(() => expect(hook.result.current.available).toBe(true));
    await act(async () => resolve({ collection: 'discovery_reads', id: 'post:telegram:old', version: 10, data: { isRead: true } }));
    expect(hook.result.current.isRead).toBe(false);
    hook.unmount();
  });
  it('keeps a new account independent while an old write is pending and rejects duplicate clicks', async () => {
    const first = new HomeDatabase(crypto.randomUUID());
    const second = new HomeDatabase(crypto.randomUUID());
    const oldChanged = vi.fn();
    mocks.sync = { db: first, changed: oldChanged } as unknown as HomeSync;
    const hook = renderHook(() => useDiscoveryPostRead('telegram', 'same', true));
    await waitFor(() => expect(hook.result.current.available).toBe(true));
    let resolve!: () => void;
    const edit = vi.spyOn(first, 'edit').mockImplementationOnce(() => new Promise<void>(done => { resolve = done; }));
    let pending!: Promise<void>;
    act(() => { pending = hook.result.current.mark(true); });
    await act(() => hook.result.current.mark(true));
    expect(edit).toHaveBeenCalledOnce();
    mocks.sync = { db: second, changed: vi.fn() } as unknown as HomeSync;
    act(() => mocks.listeners.forEach(listener => listener()));
    await waitFor(() => expect(hook.result.current.available).toBe(true));
    await act(() => hook.result.current.mark(false));
    await act(async () => { resolve(); await pending; });
    expect(hook.result.current.isRead).toBe(false);
    expect(hook.result.current.busy).toBe(false);
    expect(oldChanged).not.toHaveBeenCalled();
    expect((await second.pending())[0].data?.isRead).toBe(false);
    hook.unmount();
  });
  it('clears a read error after a successful reload', async () => {
    const db = new HomeDatabase(crypto.randomUUID());
    mocks.sync = { db, changed: vi.fn() } as unknown as HomeSync;
    vi.spyOn(db, 'getRecord').mockRejectedValueOnce(new Error('temporary'));
    const hook = renderHook(() => useDiscoveryPostRead('telegram', 'same', true));
    await waitFor(() => expect(hook.result.current.error).not.toBe(''));
    expect(hook.result.current.available).toBe(false);
    act(() => mocks.listeners.forEach(listener => listener()));
    await waitFor(() => expect(hook.result.current.available).toBe(true));
    expect(hook.result.current.error).toBe('');
    hook.unmount();
  });
  it('does not apply a completed write to a different post', async () => {
    const db = new HomeDatabase(crypto.randomUUID());
    mocks.sync = { db, changed: vi.fn() } as unknown as HomeSync;
    const hook = renderHook(({ id }) => useDiscoveryPostRead('telegram', id, true), { initialProps: { id: 'old' } });
    await waitFor(() => expect(hook.result.current.available).toBe(true));
    let finish!: () => void;
    vi.spyOn(db, 'edit').mockImplementationOnce(() => new Promise<void>(resolve => { finish = resolve; }));
    let pending!: Promise<void>;
    act(() => { pending = hook.result.current.mark(true); });
    hook.rerender({ id: 'new' });
    await waitFor(() => expect(hook.result.current.available).toBe(true));
    await act(async () => { finish(); await pending; });
    expect(hook.result.current.isRead).toBe(false);
    hook.unmount();
  });
  it('reads one key instead of cloning the complete workspace', async () => {
    const db = new HomeDatabase(crypto.randomUUID());
    mocks.sync = { db, changed: vi.fn() } as unknown as HomeSync;
    const scan = vi.spyOn(db, 'allRecords');
    const hook = renderHook(() => useDiscoveryPostRead('telegram', 'news/123', true));
    await waitFor(() => expect(hook.result.current.available).toBe(true));
    expect(scan).not.toHaveBeenCalled();
    hook.unmount();
  });
  it('projects phone read status and writes desktop toggles to the same canonical record', async () => {
    const db = new HomeDatabase(crypto.randomUUID()); const changed = vi.fn(); mocks.sync = { db, changed } as unknown as HomeSync;
    await db.applyRemote([{ collection: 'discovery_reads', id: 'post:telegram:news/123', version: 7, data: { kind: 'post', channelId: 'telegram', isRead: true } }], 1, true);
    const hook = renderHook(() => useDiscoveryPostRead('telegram', 'news/123', true));
    await waitFor(() => expect(hook.result.current.isRead).toBe(true));
    await act(() => hook.result.current.mark(false));
    expect((await db.pending())[0]).toMatchObject({ id: 'post:telegram:news/123', baseVersion: 7, data: { kind: 'post', channelId: 'telegram', isRead: false } });
    expect(changed).toHaveBeenCalledOnce(); expect(hook.result.current.isRead).toBe(false); hook.unmount();
  });
  it('responds to remote tombstones and disables the action outside an active home account', async () => {
    const db = new HomeDatabase(crypto.randomUUID()); mocks.sync = { db, changed: vi.fn() } as unknown as HomeSync;
    await db.applyRemote([{ collection: 'discovery_reads', id: 'post:x-tweet:123', version: 1, data: { kind: 'post', channelId: 'x-tweet', isRead: true } }], 1, true);
    const hook = renderHook(() => useDiscoveryPostRead('x-tweet', '123', true));
    await waitFor(() => expect(hook.result.current.isRead).toBe(true));
    await db.applyRemote([{ collection: 'discovery_reads', id: 'post:x-tweet:123', version: 2, deleted: true, data: null }], 2);
    act(() => mocks.listeners.forEach(listener => listener()));
    await waitFor(() => expect(hook.result.current.isRead).toBe(false));
    await act(() => hook.result.current.mark(true)); expect((await db.pending())[0].baseVersion).toBe(2);
    mocks.sync = null; act(() => mocks.listeners.forEach(listener => listener()));
    await waitFor(() => expect(hook.result.current.available).toBe(false)); hook.unmount();
  });
});
