import runtime from './reader-runtime.txt?raw';
import style from './reader-style.txt?raw';
import { snapshotItems, settingsSchema, resolveReadingProfile, type ReadingItem, type ReadingProfile, type ReadingSnapshot, type ReadingTheme } from './model';
import { readingIcon, readingIconSprite } from './icons';
import { repositoryDetailFields, repositoryNameParts } from '../repositoryReadingPresentation';

const escape = (value: unknown) => String(value ?? '').replace(/[&<>"']/g, ch => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[ch]!));
export function safeSourceUrl(value: string): string { try { const url = new URL(value); return ['https:', 'http:'].includes(url.protocol) && !url.username && !url.password ? url.href : ''; } catch { return ''; } }
const colorKeys = ['background', 'foreground', 'card', 'card-foreground', 'popover', 'popover-foreground', 'primary', 'primary-foreground', 'primary-emphasis', 'secondary', 'secondary-foreground', 'muted', 'muted-foreground', 'accent', 'accent-foreground', 'destructive', 'destructive-foreground', 'border', 'border-strong', 'input', 'ring', 'shadow-color', 'selection', 'selection-foreground', 'search-highlight'];
const hsl = /^-?\d+(?:\.\d+)?\s+\d+(?:\.\d+)?%\s+\d+(?:\.\d+)?%$/;
/** Values are declarations only; no CSS selectors, URLs or executable constructs. */
export function readingThemeCss(theme?: ReadingTheme): string {
  if (!theme) return '';
  const palette = (values: Record<string, string>) => colorKeys.filter(key => hsl.test(values[key] || '')).map(key => `--${key}:${values[key]}`).join(';');
  const radius = /^(?:\d+(?:\.\d+)?)(?:px|rem|em)$/.test(theme.radius) ? theme.radius : '.5rem';
  const font = (value: string, fallback: string) => value.length <= 300 && /^[\w\s,'"\u3400-\u9fff-]+$/.test(value) ? value : fallback;
  const shadow = theme.shadow.length <= 250 && /^[\d\s.,()%/#a-z-]+$/i.test(theme.shadow) && !/url|expression|@|[;{}<>]/i.test(theme.shadow) && [...theme.shadow.matchAll(/var\(([^)]+)\)/g)].every(match => ['--shadow-color', '--shadow-opacity'].includes(match[1])) ? theme.shadow : '0 1px 3px hsl(var(--foreground) / .04)';
  return `:root{--radius:${radius};--app-shadow:${shadow};--font-sans:${font(theme.fontSans, 'system-ui,sans-serif')};--font-mono:${font(theme.fontMono, 'ui-monospace,monospace')}}body[data-mode="light"]{${palette(theme.light)}}body[data-mode="dark"]{${palette(theme.dark)}}`;
}
function firstCard(item: ReadingItem, snapshot: ReadingSnapshot, profile: ReadingProfile): string {
  const { owner, name } = repositoryNameParts(item.name);
  const body = profile.cardFields.map(key => {
    if (key === 'summary') return item.summary || item.description ? `<span class="summary">${escape(item.summary || item.description)}</span>` : '';
    if (key === 'description') return !item.summary && !profile.cardFields.includes('summary') && item.description ? `<span class="summary">${escape(item.description)}</span>` : '';
    if (key === 'tags' || key === 'category') return `<span class="tags">${(key === 'tags' ? item.tags.slice(0,3) : item.category ? [item.category] : []).map(tag=>`<span>${escape(tag)}</span>`).join('')}</span>`;
    if (key === 'language') return item.language ? `<span class="meta language"><i></i>${escape(item.language)}</span>` : '';
    if (key === 'stars') return `<span class="meta">${readingIcon('star')}${Number(item.stars || 0).toLocaleString('zh-CN')}</span>`;
    return item.updated ? `<span class="meta">更新 ${escape(item.updated.slice(0,10))}</span>` : '';
  }).join('');
  return `<article class="project" data-id="${item.id}"><button class="card-main" data-open="${item.id}"><span class="project-heading"><span class="avatar">${escape((owner || name).slice(0,1).toUpperCase())}</span><span class="project-identity"><strong>${escape(name)}</strong>${owner ? `<span class="owner">${escape(owner)}</span>` : ''}</span>${readingIcon('chevron')}</span>${body}<span class="meta" data-read="${item.id}">${item.state.read ? '已读' : ''}</span></button><div class="card-actions">${snapshot.settings.operations.interest ? `<button data-action="interest" data-repo="${item.id}" aria-pressed="${item.state.interest === 'interested'}">${readingIcon('heart')}感兴趣</button>` : ''}${snapshot.settings.operations.candidate ? `<button data-action="candidate" data-repo="${item.id}" aria-pressed="${item.state.candidate}">${readingIcon('bookmark')}收藏候选</button>` : ''}</div></article>`;
}
export function renderReadingHtml(snapshot: ReadingSnapshot): string {
  const normalized = settingsSchema.parse(snapshot.settings);
  snapshot = { ...snapshot, settings: normalized, sections: snapshot.sections.map(section => ({ ...section, presentation: section.presentation ?? resolveReadingProfile(normalized, section.id) })) };
  const settings = snapshot.settings;
  const allItems = new Map(snapshotItems(snapshot).map(item => [item.id, item]));
  const firstSection = settings.initialPage === 'discovery' ? snapshot.sections.find(section => section.id !== 'repositories') : snapshot.sections.find(section => section.id === 'repositories');
  const section = firstSection || snapshot.sections[0];
  const entries = section?.editions?.[0]?.entries || section?.entries;
  const initialItems = entries ? entries.flatMap(entry => allItems.has(entry.repoId) ? [allItems.get(entry.repoId)!] : []) : section?.items || [];
  const payload = JSON.stringify(snapshot).replace(/</g, '\\u003c').replace(/\u2028/g, '\\u2028').replace(/\u2029/g, '\\u2029');
  const mode = settings.theme === 'dark' ? 'dark' : settings.theme === 'light' ? 'light' : snapshot.theme?.mode || 'light';
  const date = Number.isFinite(Date.parse(snapshot.generatedAt)) ? new Date(snapshot.generatedAt).toLocaleDateString('zh-CN', { timeZone: 'Asia/Shanghai', month: 'long', day: 'numeric' }) : '';
  return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; img-src data:; connect-src 'none'; base-uri 'none'; form-action 'none'"><title>${escape(snapshot.title)}</title><style>${style}\n${readingThemeCss(snapshot.theme)}</style></head>
<body data-mode="${mode}" data-theme="${escape(settings.theme)}" data-density="${settings.density}" ${snapshot.theme?.reducedMotion ? 'data-reduced-motion="true"' : ''} style="--size:${settings.fontSize}px;--summary-lines:${settings.summaryLines || 6}">${readingIconSprite}
<header class="app-header"><div class="header-inner"><div class="header-title"><h1 id="page-title">${settings.initialPage === 'discovery' ? '发现' : '仓库'}</h1><span class="edition-date">${escape(date)}</span></div><div class="header-actions"><button id="search-toggle" class="icon-button" aria-label="展开搜索" aria-expanded="false" aria-controls="search-row">${readingIcon('search')}</button><button id="category-open" class="icon-button" aria-label="选择分类">${readingIcon('filter')}</button><button id="channels-open" class="icon-button" aria-label="全部发现频道" hidden>${readingIcon('menu')}</button><button id="info" class="icon-button" aria-label="快照信息与主题">${readingIcon('info')}</button><button id="export" class="export-button">${readingIcon('export')}<span>导出</span><span id="pending-count" class="badge" hidden></span></button></div></div><div id="search-row" class="search-row" hidden><label class="search-box">${readingIcon('search')}<input id="search" type="search" aria-label="搜索项目" placeholder="搜索项目名称、用途或标签"><button id="clear-search" type="button" class="icon-button" aria-label="清空搜索" hidden>${readingIcon('close')}</button></label></div><nav id="channel-tabs" class="channel-tabs" aria-label="发现频道" hidden></nav></header>
<p id="notice" role="status" class="notice" hidden></p><noscript><p class="notice">当前预览不支持脚本。请下载后使用浏览器打开，以使用频道、详情、标记和导出。</p></noscript>
<main id="list-page"><div class="list-heading"><button id="reading-view-open" class="icon-button" aria-label="阅读视图">${readingIcon('filter')}</button><h2 id="section-title">${escape(section?.title || '仓库')}</h2><span id="result-count" class="muted">${initialItems.length} 个项目</span></div><div id="edition-row" class="edition-row" hidden><label for="edition-select">期刊</label><select id="edition-select" aria-label="选择期刊"></select><span id="edition-status" class="muted"></span></div><p id="section-warning" class="notice" hidden></p><div id="filter-chips" class="filter-chips"></div><div id="list-top-spacer" aria-hidden="true"></div><div id="project-grid" class="grid">${initialItems.slice(0, 40).map(item => firstCard(item, snapshot, section!.presentation!)).join('')}</div><div id="list-bottom-spacer" aria-hidden="true"></div><p id="empty" class="empty-state" hidden>没有匹配项目，试试其他关键词或分类。</p><button id="load-more" class="load-more">继续浏览</button><p id="list-end" class="list-end muted" hidden>已浏览本列表全部项目</p></main>
<nav class="bottom-nav" aria-label="主导航">${settings.repositories ? `<button data-page="repositories">${readingIcon('repository')}<span>仓库</span></button>` : ''}${settings.discovery ? `<button data-page="discovery">${readingIcon('compass')}<span>发现</span></button>` : ''}</nav>
<section id="detail-page" class="detail-page" hidden aria-label="项目详情"><header class="detail-header"><button id="detail-back" class="icon-button" aria-label="返回项目列表">${readingIcon('arrow')}</button><div id="detail-title"></div><button id="detail-options-open" class="icon-button" aria-label="详情操作菜单">${readingIcon('menu')}</button><a id="detail-github" class="icon-button" target="_blank" rel="noopener noreferrer" aria-label="在 GitHub 查看">${readingIcon('external')}</a></header><nav id="detail-tabs" class="detail-tabs" aria-label="分析分区"></nav><div id="detail-scroll" class="detail-scroll"><div id="detail-hero"></div><div id="detail-content"></div><div id="detail-reading" class="reading-panel"></div></div></section>
<dialog id="detail-options" aria-label="详情操作"><div class="dialog-heading"><h2>详情操作</h2><button data-close-dialog class="icon-button" aria-label="关闭">${readingIcon('close')}</button></div><button id="previous-project">上一个项目</button><button id="next-project">下一个项目</button><p id="detail-index" class="muted"></p><h3 class="outline-title">本分区目录</h3><div id="detail-outline"></div></dialog>
<dialog id="drawer" class="drawer" aria-labelledby="drawer-title"><div class="dialog-heading"><h2 id="drawer-title"></h2><button data-close-dialog class="icon-button" aria-label="关闭">${readingIcon('close')}</button></div><div id="drawer-content"></div></dialog>
<dialog id="information" aria-labelledby="information-title"><div class="dialog-heading"><h2 id="information-title">快照与阅读记录</h2><button data-close-dialog class="icon-button" aria-label="关闭">${readingIcon('close')}</button></div><p>${escape(snapshot.title)}</p><p class="muted">${escape(snapshot.generatedAt)} · 内容来自桌面已有资料</p><p id="section-description" class="muted"></p><button id="theme" class="theme-control" aria-label="切换明暗主题">${readingIcon('moon')}切换明暗主题</button><div id="snapshot-warnings"></div><p id="change-status" role="status"></p><p class="muted">手机修改和继续阅读位置需要导出并带回桌面。收藏候选回到桌面后另行确认。</p><label class="restore">载入这份 HTML 的回传记录<input id="restore" type="file" accept="application/json,.json"></label></dialog>
<dialog id="return-dialog" aria-labelledby="export-title"><div class="dialog-heading"><h2 id="export-title">带回桌面</h2><button data-close-dialog class="icon-button" aria-label="关闭">${readingIcon('close')}</button></div><p class="muted">复制到桌面设置 → 每日 HTML → 回传，或下载 JSON 后批量导入。每份日报独立保存记录。</p><p id="export-history" class="muted"></p><textarea id="return-text" aria-label="回传文本" readonly></textarea><div class="export-actions"><button id="copy">${readingIcon('copy')}复制文本</button><button id="download">${readingIcon('export')}下载回传文件</button><button id="close-export">关闭</button></div><p id="export-status" role="status"></p></dialog>
<div id="toast" class="toast" role="status" hidden></div><script id="gsm-data" type="application/json">${payload}</script><script id="gsm-presentation" type="application/json">${JSON.stringify(repositoryDetailFields)}</script><script>${runtime}</script></body></html>`;
}
