import { beforeEach, describe, expect, it, vi } from 'vitest';
import { IDBFactory } from 'fake-indexeddb';
import { defaultSettings, emptyReadingState, parseReadingReturn, type ReadingReturn, type ReadingSnapshot } from './model';
import { applyReadingReturn, inspectReadingReturn, loadReadingData, readingTransaction, rememberSnapshot, saveReadingSettings } from './storage';
beforeEach(()=>{vi.stubGlobal('indexedDB',new IDBFactory());});
const snapshot=():ReadingSnapshot=>({version:1,id:'snapshot',accountId:'42',generatedAt:'2026-09-30T00:00:00Z',title:'GSM',settings:structuredClone(defaultSettings),sections:[{id:'repositories',title:'仓库',updatedAt:'',items:[{id:1,name:'acme/tool',url:'https://github.com/acme/tool',categoryId:'none',category:'',summary:'',description:'',tags:[],language:'',stars:1,updated:'',analysis:[],sources:[],generatedAt:'',reason:'',state:emptyReadingState()}]}]});
const incoming=(field:ReadingReturn['operations'][number]['field']='read',value:string|boolean=true):ReadingReturn=>({format:'gsm-reading-changes',version:1,accountId:'42',snapshotId:'snapshot',operations:[{id:'18ee370a-f449-4c76-b7dc-1b6903dc681b',repoId:1,field,base:field==='note'?'':field==='interest'?'neutral':false,value}]});
describe('HTML reading round trip',()=>{
  it('persists preferences by account and does not include credentials',async()=>{await saveReadingSettings('42',{...defaultSettings,fontSize:'20'});expect((await loadReadingData('42')).settings.fontSize).toBe('20');expect((await loadReadingData('43')).settings.fontSize).toBe('16');expect(JSON.stringify(await loadReadingData('42'))).not.toContain('password');});
  it('imports operations once and preserves unrelated notes',async()=>{await rememberSnapshot('42',snapshot());await readingTransaction('42',d=>{d.states['2']={...emptyReadingState(),note:'keep'};});expect(await applyReadingReturn('42',incoming(),{})).toEqual({applied:1,duplicate:0,kept:0});expect(await applyReadingReturn('42',incoming(),{})).toEqual({applied:0,duplicate:1,kept:0});expect((await loadReadingData('42')).states['2'].note).toBe('keep');});
  it('preserves both note versions until the user resolves conflict',async()=>{await rememberSnapshot('42',snapshot());await readingTransaction('42',d=>{d.states['1']={...emptyReadingState(),note:'desktop'};});const input=incoming('note','phone');const rows=inspectReadingReturn(await loadReadingData('42'),'42',input);expect(rows[0].status).toBe('conflict');await expect(applyReadingReturn('42',input,{})).rejects.toThrow('冲突');expect((await loadReadingData('42')).states['1'].note).toBe('desktop');await applyReadingReturn('42',input,{[input.operations[0].id]:'phone'});expect((await loadReadingData('42')).states['1'].note).toBe('phone');});
  it('rejects changes made on desktop after import preview',async()=>{await rememberSnapshot('42',snapshot());const input=incoming('note','phone');const rows=inspectReadingReturn(await loadReadingData('42'),'42',input);await readingTransaction('42',d=>{d.states['1']={...emptyReadingState(),note:'later'};});await expect(applyReadingReturn('42',input,{},rows)).rejects.toThrow('预览后');});
  it('keeps desktop version and receipts that decision',async()=>{await rememberSnapshot('42',snapshot());await readingTransaction('42',d=>{d.states['1']={...emptyReadingState(),interest:'ignored'};});const input=incoming('interest','interested');await applyReadingReturn('42',input,{[input.operations[0].id]:'desktop'});expect((await loadReadingData('42')).states['1'].interest).toBe('ignored');expect((await applyReadingReturn('42',input,{})).duplicate).toBe(1);});
  it.each(['wrong-account','unknown-snapshot','unknown-repo','wrong-base','invalid-field-value','disabled-operation','changed-receipt','duplicate-target'])('rejects %s without modifying state',async kind=>{const s=snapshot();if(kind==='disabled-operation')s.settings.operations.read=false;await rememberSnapshot('42',s);const input=incoming();if(kind==='wrong-account')input.accountId='43';if(kind==='unknown-snapshot')input.snapshotId='missing';if(kind==='unknown-repo')input.operations[0].repoId=9;if(kind==='wrong-base')input.operations[0].base=true;if(kind==='invalid-field-value')input.operations[0].value='true';if(kind==='changed-receipt'){await applyReadingReturn('42',input,{});input.operations[0].value=false;}if(kind==='duplicate-target')input.operations.push({...input.operations[0],id:'584a5f7b-39cb-44d9-b651-0e29cce5e8ae'});await expect(applyReadingReturn('42',input,{})).rejects.toThrow();});
  it('rejects oversized or unsupported return formats',()=>{expect(()=>parseReadingReturn(' '.repeat(4000001))).toThrow('4 MB');expect(()=>parseReadingReturn('{"format":"backup"}')).toThrow();});
});
