import { act, renderHook, waitFor } from '@testing-library/react';
import { beforeEach, expect, it, vi } from 'vitest';
import { IDBFactory } from 'fake-indexeddb';
import { readingTransaction, loadReadingData } from '../../../lib/html-reading/storage';
const mocks=vi.hoisted(()=>({state:{isAuthenticated:true,user:{id:42},githubToken:'synthetic',repositories:[{id:1,ai_summary:'existing'}],discoveryRepos:{},addRepository:vi.fn()},api:{getRepository:vi.fn(),starRepository:vi.fn()}}));
vi.mock('../../../store/useAppStore',()=>({useAppStore:Object.assign((selector:(s:typeof mocks.state)=>unknown)=>selector(mocks.state),{getState:()=>mocks.state})}));
vi.mock('../../../services/htmlReading',()=>({readingAccount:()=>String(mocks.state.user.id),readingCatalog:async()=>({categories:[],channels:[]}),generateReadingSnapshot:vi.fn(),prepareReadingSend:vi.fn(),downloadReadingHtml:vi.fn()}));
vi.mock('../../../services/githubApiFactory',()=>({createGitHubApiService:()=>mocks.api}));
import { useHtmlReading } from './useHtmlReading';
beforeEach(async()=>{vi.stubGlobal('indexedDB',new IDBFactory());window.electronAPI=undefined;mocks.state.user={id:42};mocks.state.addRepository.mockReset();mocks.api.getRepository.mockReset();mocks.api.getRepository.mockResolvedValue({id:1,full_name:'acme/tool'});mocks.api.starRepository.mockReset();mocks.api.starRepository.mockResolvedValue(undefined);vi.spyOn(window,'confirm').mockReturnValue(true);await readingTransaction('42',data=>{data.names['1']='acme/tool';data.states['1']={read:false,note:'keep',interest:'interested',candidate:true};});});
async function controller(){const hook=renderHook(()=>useHtmlReading());await waitFor(()=>expect(hook.result.current.ready).toBe(true));return hook;}
it('does not contact GitHub when explicit Star confirmation is declined',async()=>{vi.mocked(window.confirm).mockReturnValue(false);const c=await controller();await act(()=>c.result.current.star('1'));expect(mocks.api.getRepository).not.toHaveBeenCalled();expect(mocks.api.starRepository).not.toHaveBeenCalled();expect((await loadReadingData('42')).states['1'].candidate).toBe(true);});
it('rejects a repository name whose GitHub numeric identity changed',async()=>{mocks.api.getRepository.mockResolvedValue({id:2});const c=await controller();await act(()=>c.result.current.star('1'));expect(mocks.api.starRepository).not.toHaveBeenCalled();expect(c.result.current.error).toContain('项目标识已变化');expect((await loadReadingData('42')).states['1'].candidate).toBe(true);});
it('does not Star after the active account changed during lookup',async()=>{mocks.api.getRepository.mockImplementation(async()=>{mocks.state.user={id:43};return{id:1};});const c=await controller();await act(()=>c.result.current.star('1'));expect(mocks.api.starRepository).not.toHaveBeenCalled();expect((await loadReadingData('42')).states['1'].candidate).toBe(true);});
it('confirms Star without replacing an existing repository analysis or reading note',async()=>{const c=await controller();await act(()=>c.result.current.star('1'));expect(mocks.api.starRepository).toHaveBeenCalledWith('acme','tool');expect(mocks.state.addRepository).not.toHaveBeenCalled();expect(mocks.state.repositories[0].ai_summary).toBe('existing');expect((await loadReadingData('42')).states['1']).toMatchObject({candidate:false,note:'keep'});});
it('does not modify the new account if account changes while GitHub accepts Star',async()=>{mocks.api.starRepository.mockImplementation(async()=>{mocks.state.user={id:43};});const c=await controller();await act(()=>c.result.current.star('1'));expect(mocks.state.addRepository).not.toHaveBeenCalled();expect((await loadReadingData('42')).states['1'].candidate).toBe(true);expect((await loadReadingData('43')).states).toEqual({});});
