import type { ReactNode } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '../ui/card';
import { Checkbox } from '../ui/checkbox';
import { Input } from '../ui/input';
export function ReadingGroup({title,description,children}:{title:string;description?:string;children:ReactNode}) {return <Card><CardHeader><CardTitle className="text-base">{title}</CardTitle>{description&&<p className="text-sm text-muted-foreground">{description}</p>}</CardHeader><CardContent className="space-y-4">{children}</CardContent></Card>;}
export function ReadingToggle({label,checked,onChange,hint}:{label:string;checked:boolean;onChange:(value:boolean)=>void;hint?:string}) {return <label className="flex cursor-pointer items-start gap-3 rounded-md border border-border px-3 py-2.5"><Checkbox checked={checked} onCheckedChange={value=>onChange(value===true)} aria-label={label} className="mt-1"/><span className="min-w-0"><span className="block text-sm font-medium">{label}</span>{hint&&<span className="mt-1 block text-xs text-muted-foreground">{hint}</span>}</span></label>;}
export function ReadingFlags<T extends string>({labels,values,onChange}:{labels:Record<T,string>;values:Record<T,boolean>;onChange:(key:T,value:boolean)=>void}) {return <div className="grid grid-cols-1 gap-2 sm:grid-cols-2">{(Object.entries(labels) as Array<[T,string]>).map(([key,label])=><ReadingToggle key={key} label={label} checked={values[key]} onChange={value=>onChange(key,value)}/>)}</div>;}
export function ReadingNumber({label,value,min,max,onChange}:{label:string;value:number;min:number;max:number;onChange:(value:number)=>void}) {return <label className="block space-y-2 text-sm"><span>{label}</span><Input type="number" min={min} max={max} value={value} onChange={e=>onChange(Number(e.target.value))}/></label>;}
export function ReadingSelect({label,value,onChange,options}:{label:string;value:string;onChange:(value:string)=>void;options:Array<[string,string]>}) {return <label className="block space-y-2 text-sm"><span>{label}</span><select className="h-10 w-full rounded-md border border-input bg-background px-3 text-sm" value={value} onChange={e=>onChange(e.target.value)}>{options.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label>;}
