import { useT } from '../../i18n/useT';
import { translateReadingLabels } from './htmlReadingLabels';
import { cardFields, detailFields, type ReadingProfile, type ReadingProfileOverride } from '../../lib/html-reading/model';
import { Button } from '../ui/button';
import { ReadingGroup, ReadingNumber, ReadingSelect, ReadingToggle } from './HtmlReadingFields';
import { useState, type ReactNode } from 'react';

export function ReadingAdvanced({ title, children }: { title: string; children: ReactNode }) {
  const [open, setOpen] = useState(false);
  return <details className="my-3 rounded-lg border p-3" onToggle={event => setOpen(event.currentTarget.open)}><summary className="cursor-pointer py-2 text-sm font-medium">{title}</summary>{open && children}</details>;
}

export function HtmlReadingProfile({ title, inherited, override, onChange, quantity = false }: { title: string; inherited: ReadingProfile; override: ReadingProfileOverride; onChange: (value: ReadingProfileOverride) => void; quantity?: boolean }) {
  const t=useT('settings');
  const cardLabels=translateReadingLabels(cardFields,'card',t);
  const detailLabels=translateReadingLabels(detailFields,'detail',t);
  const fields = override.cardFields ?? inherited.cardFields;
  const order = override.detailOrder ? [...override.detailOrder, ...inherited.detailOrder.filter(key => !override.detailOrder!.includes(key))] : inherited.detailOrder;
  const move = <T extends string,>(values: T[], index: number, direction: number): T[] => { const result = [...values]; [result[index], result[index + direction]] = [result[index + direction], result[index]]; return result; };
  const modeLabel={expanded:t('htmlReadingUi.expanded'),collapsed:t('htmlReadingUi.collapsed'),omit:t('htmlReadingUi.omitted')};
  return <ReadingGroup title={title} description={t('htmlReadingUi.settingsWithoutOverridesInheritFromTheParent')}>
    <div className="flex flex-wrap items-center gap-2"><Button variant="outline" size="sm" disabled={!Object.keys(override).length} onClick={() => onChange({})}>{t('htmlReadingUi.resetAllOverrides')}</Button><span className="text-xs text-muted-foreground">{Object.keys(override).length ? t('htmlReadingUi.overridesExist') : t('htmlReadingUi.allInherited')}</span></div>
    {quantity && <><div className="grid gap-3 sm:grid-cols-2"><ReadingNumber label={t('htmlReadingUi.itemLimitPerChannelEdition')} min={1} max={500} value={override.perChannel ?? inherited.perChannel} onChange={value => onChange({ ...override, perChannel: value })}/><ReadingNumber label={t('htmlReadingUi.maximumHistoryEditionsAlsoLimitedByHistory')} min={1} max={90} value={override.historyCount ?? inherited.historyCount} onChange={value => onChange({ ...override, historyCount: value })}/></div><p className="text-xs text-muted-foreground">{t('htmlReadingUi.effectiveCountPerChannelEdition')}{override.perChannel??inherited.perChannel} {t('htmlReadingUi.items')}{override.perChannel===undefined?t('htmlReadingUi.inheritedFromParent'):t('htmlReadingUi.overridden')}{t('htmlReadingUi.atMost')}{override.historyCount??inherited.historyCount} {t('htmlReadingUi.editions')}{override.historyCount===undefined?t('htmlReadingUi.inheritedFromParent'):t('htmlReadingUi.overridden')}）</p><Button size="sm" variant="ghost" onClick={() => { const next = { ...override }; delete next.perChannel; delete next.historyCount; onChange(next); }}>{t('htmlReadingUi.resetCountOverrides')}</Button></>}
    <p className="text-sm font-medium">{t('htmlReadingUi.cardContentAndOrderSummariesRemainComplete')}</p><p className="text-xs text-muted-foreground">{t('htmlReadingUi.effectiveCards')}{override.cardFields?t('htmlReadingUi.overridden'):t('htmlReadingUi.inheritedFromParent')}）：{fields.map(key=>cardLabels[key]).join(' → ')||t('htmlReadingUi.none')}</p>
    <div className="grid gap-2 sm:grid-cols-2">{Object.entries(cardLabels).filter(([key]) => key !== 'description').map(([key, label]) => <ReadingToggle key={key} label={label} checked={fields.includes(key as keyof typeof cardFields)} onChange={checked => onChange({ ...override, cardFields: checked ? [...fields, key as keyof typeof cardFields] : fields.filter(field => field !== key) })}/>)}</div>
    <div className="space-y-1">{fields.map((key, index) => <div key={key} className="flex items-center gap-2 rounded border px-3 py-1 text-sm"><span className="flex-1">{cardLabels[key]}</span><Button variant="ghost" size="sm" aria-label={t('htmlReadingUi.moveCardUp', { v1: title, v2: cardLabels[key] })} disabled={index === 0} onClick={() => onChange({ ...override, cardFields: move(fields, index, -1) })}>{t('htmlReadingUi.moveUp')}</Button><Button variant="ghost" size="sm" aria-label={t('htmlReadingUi.moveCardDown', { v1: title, v2: cardLabels[key] })} disabled={index === fields.length - 1} onClick={() => onChange({ ...override, cardFields: move(fields, index, 1) })}>{t('htmlReadingUi.moveDown')}</Button></div>)}</div>
    <Button variant="ghost" size="sm" onClick={() => { const next = { ...override }; delete next.cardFields; onChange(next); }}>{t('htmlReadingUi.resetCardOverrides')}</Button>
    <p className="text-sm font-medium">{t('htmlReadingUi.detailSectionsAndOrderOrderWithinSections')}</p>
    <p className="text-xs text-muted-foreground">{t('htmlReadingUi.sectionOrder')}{override.detailOrder?t('htmlReadingUi.overridden'):t('htmlReadingUi.inheritedFromParent')}</p><div className="space-y-2">{order.map((key, index) => <div key={key} className="grid items-end gap-2 rounded border p-3 sm:grid-cols-[1fr_auto]"><ReadingSelect label={detailLabels[key]} value={override.detailModes?.[key] ?? 'inherit'} options={[["inherit",t('htmlReadingUi.inherit', { v1: { expanded: t('htmlReadingUi.expanded'), collapsed: t('htmlReadingUi.collapsed'), omit: t('htmlReadingUi.omitted') }[inherited.detailModes[key]] })],["expanded",t('htmlReadingUi.expanded')],["collapsed",t('htmlReadingUi.collapsed')],["omit",t('htmlReadingUi.omitted')]]} onChange={value => { const modes = { ...override.detailModes }; if (value === 'inherit') delete modes[key]; else modes[key] = value as 'expanded' | 'collapsed' | 'omit'; onChange({ ...override, detailModes: modes }); }}/><p className="text-xs text-muted-foreground sm:col-span-2">{t('htmlReadingUi.effective')}{modeLabel[override.detailModes?.[key]??inherited.detailModes[key]]} · {override.detailModes?.[key]?t('htmlReadingUi.overridden'):t('htmlReadingUi.inheritedFromParent')}</p><div className="flex gap-1"><Button size="sm" variant="ghost" aria-label={t('htmlReadingUi.moveDetailUp', { v1: title, v2: detailLabels[key] })} disabled={index === 0 || key === 'notes'} onClick={() => onChange({ ...override, detailOrder: move(order, index, -1) })}>{t('htmlReadingUi.moveUp')}</Button><Button size="sm" variant="ghost" aria-label={t('htmlReadingUi.moveDetailDown', { v1: title, v2: detailLabels[key] })} disabled={index === order.length - 1 || key === 'notes'} onClick={() => onChange({ ...override, detailOrder: move(order, index, 1) })}>{t('htmlReadingUi.moveDown')}</Button></div></div>)}</div>
    <Button variant="ghost" size="sm" onClick={() => { const next = { ...override }; delete next.detailModes; onChange(next); }}>{t('htmlReadingUi.resetDetailSectionOverrides')}</Button>
    <Button variant="ghost" size="sm" onClick={() => { const next = { ...override }; delete next.detailOrder; onChange(next); }}>{t('htmlReadingUi.resetDetailOrderOverrides')}</Button>
  </ReadingGroup>;
}
