import { translateReadingLabels } from './htmlReadingLabels';
import { FileText, Download, Eye, Save, Loader2 } from 'lucide-react';
import { useHtmlReading } from '../../features/settings/hooks/useHtmlReading';
import { detailFields, operationFields, resolveReadingProfile, resetReadingPresentation } from '../../lib/html-reading/model';
import { ReadingFlags, ReadingGroup, ReadingNumber, ReadingSelect, ReadingToggle } from './HtmlReadingFields';
import { HtmlReadingProfile, ReadingAdvanced } from './HtmlReadingProfile';
import { HtmlReadingImport } from './HtmlReadingImport';
import { HtmlReadingMail } from './HtmlReadingMail';
import { Button } from '../ui/button';
import { Input } from '../ui/input';
import { useState } from 'react';
import { useT, type TranslateFn } from '../../i18n/useT';
import { downloadReadingPreview, openReadingBrowserPreview } from './htmlReadingBrowserPreview';

function nextBeijingSchedule(time: string, t: TranslateFn) {
  const shifted = new Date(Date.now() + 8 * 60 * 60 * 1000);
  const [hours, minutes] = time.split(':').map(Number);
  const next = new Date(Date.UTC(shifted.getUTCFullYear(), shifted.getUTCMonth(), shifted.getUTCDate(), hours, minutes));
  if (next.getTime() <= shifted.getTime()) next.setUTCDate(next.getUTCDate() + 1);
  return t('htmlReadingUi.beijingTime154', { v1: next.toISOString().slice(0,10), v2: time });
}

export function HtmlReadingPanel() {
  const t = useT('settings');
  const detailLabels=translateReadingLabels(detailFields,'detail',t);
  const operationLabels=translateReadingLabels(operationFields,'operation',t);
  const [section, setSection] = useState('overview');
  const [pendingPreset, setPendingPreset] = useState<'browse' | 'deep' | null>(null);
  const [previewOpenError,setPreviewOpenError]=useState('');
  const c=useHtmlReading();const s=c.settings;const set=c.setSettings;
  const dirty=JSON.stringify(s)!==JSON.stringify(c.saved);
  const credential=c.mail.credential?.accountId===c.account?c.mail.credential:null;
  const latestRun=(c.mail.runs??[]).filter(run=>run.accountId===c.account)[0];
  const issues=[...(c.error?[c.error]:[]),...(!s.repositories&&!s.discovery?[t('htmlReadingUi.enableAtLeastOneReadingPage')]:[]),...(s.discovery&&!s.channelIds.length?[t('htmlReadingUi.noChannelsAreSelectedForTheDiscovery')]:[]),...(c.saved.scheduleEnabled&&!credential?[t('htmlReadingUi.scheduledDeliveryIsEnabledButEmailIs')]:[]),...(['failed','unconfirmed','interrupted'].includes(latestRun?.status??'')?[latestRun?.error??t('htmlReadingUi.theLatestEmailDeliveryWasNotConfirmed')]:[])];
  const select=(key:'categoryIds'|'channelIds',id:string,value:boolean)=>set(old=>({...old,[key]:value?[...old[key],id]:old[key].filter(x=>x!==id)}));
  const reopenPreview=async()=>{
    if(!c.preview)return;
    setPreviewOpenError('');
    try{const result=await window.electronAPI?.htmlReading?.preview?.(c.preview.html);if(!result?.success)setPreviewOpenError(result?.error??t('htmlReadingUi.theSeparatePreviewCouldNotBeOpened'));}
    catch(error){setPreviewOpenError(error instanceof Error?error.message:t('htmlReadingUi.theSeparatePreviewCouldNotBeOpened'));}
  };
  if(!c.account)return <p className="p-4 text-muted-foreground">{t('htmlReadingUi.signInToGithubBeforeConfiguringDaily')}</p>;
  if(!c.ready)return <div className="space-y-3 p-4"><p role={c.error?'alert':'status'} className="text-muted-foreground">{c.error||t('htmlReadingUi.loadingDailyHtmlSettingsForThisAccount')}</p>{c.error&&<Button variant="outline" disabled={c.busy} onClick={c.retryLoad}>{t('htmlReadingUi.reload')}</Button>}</div>;
  return <div className="space-y-5">
    <div className="flex items-start gap-3"><FileText className="mt-1 h-6 w-6 shrink-0 text-muted-foreground"/><div><h3 className="text-lg font-semibold">{t('htmlReadingUi.dailyHtml')}</h3><p className="mt-1 text-sm text-muted-foreground">{t('htmlReadingUi.chooseContentAppearanceAndReturnActionsFor')}</p></div></div>
    <div className="sticky top-14 z-10 flex flex-wrap items-center gap-2 rounded-lg border bg-background p-3"><Button disabled={c.busy} onClick={c.save}><Save className="mr-2 h-4 w-4"/>{t('htmlReadingUi.saveSettings')}</Button><Button variant="outline" disabled={c.busy} onClick={()=>c.generate('preview',false,'current')}><Eye className="mr-2 h-4 w-4"/>{t('htmlReadingUi.previewHtml')}</Button><Button variant="outline" disabled={c.busy} onClick={()=>c.generate('export',false,'current')}><Download className="mr-2 h-4 w-4"/>{t('htmlReadingUi.exportHtml')}</Button>{c.busy?<span className="flex items-center gap-2 text-xs" role="status"><Loader2 className="h-4 w-4 animate-spin"/>{c.progress || t('htmlReadingUi.processing')}</span>:<span className="text-xs text-muted-foreground">{dirty?t('htmlReadingUi.unsavedSettingsPreviewAndManualExportUse'):t('htmlReadingUi.saved')}</span>}{c.canCancel&&<Button variant="ghost" onClick={c.cancelGeneration}>{t('htmlReadingUi.cancelGeneration')}</Button>}</div>
    {c.error&&<p role="alert" className="rounded-md border border-destructive/30 p-3 text-sm text-destructive">{c.error}</p>}{c.message&&<p role="status" className="rounded-md bg-muted p-3 text-sm">{c.message}</p>}
    {c.generationReport && <details className="rounded-md border p-3 text-sm"><summary className="cursor-pointer">{t('htmlReadingUi.contentCheck')}{c.generationReport.reduce((n,row)=>n+row.count,0)} {t('htmlReadingUi.projectEntries')}{c.generationReport.filter(row=>row.warning).length} {t('htmlReadingUi.notices')}{c.reportStale?t('htmlReadingUi.configurationChangedCheckAgain'):''}</summary><p className="mt-2 text-xs text-muted-foreground">{c.reportStale?t('htmlReadingUi.thisCheckUsesTheEarlierGenerationConfiguration'):t('htmlReadingUi.thisCheckUsesTheCurrentEffectiveForm')}</p><Button variant="link" size="sm" onClick={()=>setSection('channels')}>{t('htmlReadingUi.viewChannelConfigurationAndEffectiveValues')}</Button><div className="mt-2 space-y-2">{c.generationReport.map(row=><div key={row.id}><p>{row.title} {t('htmlReadingUi.target')}{row.target ?? '—'} {t('htmlReadingUi.available')}{row.available ?? row.count} {t('htmlReadingUi.exported')}{row.count}</p><p className="text-xs text-muted-foreground">{row.updatedAt?t('htmlReadingUi.sourceTimeBeijingTime', { v1: new Date(row.updatedAt).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai'}) }):t('htmlReadingUi.sourceTimeNotRecorded')}{row.sourceStatus?t('htmlReadingUi.sourceStatus', { v1: {cached:t('htmlReadingUi.usingCache'),updated:t('htmlReadingUi.updated'),partial:t('htmlReadingUi.partialResults'),empty:t('htmlReadingUi.noResults'),unavailable:t('htmlReadingUi.unavailable')}[row.sourceStatus]??row.sourceStatus }):''}{row.fetched!==undefined?t('htmlReadingUi.fetchedItems', { v1: row.fetched }):''}{row.unanalyzed!==undefined?t('htmlReadingUi.itemsWithoutAiSummaryOrAnalysis', { v1: row.unanalyzed }):''}</p>{row.warning && <p className="text-xs text-muted-foreground">{row.warning}</p>}</div>)}</div></details>}
    {c.sizeDiagnostic&&<details open className="space-y-2 rounded-md border p-3 text-sm"><summary>{t('htmlReadingUi.attachmentSizeDiagnostics')}</summary><p className="text-xs text-muted-foreground">{t('htmlReadingUi.theseAreSerializedContentSizeEstimatesAdjust')}</p>{Object.entries(c.sizeDiagnostic.sections).sort((a,b)=>b[1]-a[1]).map(([id,bytes])=><p key={id}>{id==='repositories'?t('htmlReadingUi.starredRepositories'):c.catalog.channels.find(channel=>channel.id===id)?.name??id} · {(bytes/1024/1024).toFixed(2)} MB</p>)}{Object.entries(c.sizeDiagnostic.fields).sort((a,b)=>b[1]-a[1]).slice(0,6).map(([field,bytes])=><p key={field}>{({...detailLabels,analysis:t('htmlReadingUi.analysisContent'),state:t('htmlReadingUi.readingRecords'),sourceProvenance:t('htmlReadingUi.sourceInformation'),dailyChange:t('htmlReadingUi.dailyChanges'),name:t('htmlReadingUi.projectName'),url:t('htmlReadingUi.projectUrl'),id:t('htmlReadingUi.projectId'),categoryId:t('htmlReadingUi.categoryId'),generatedAt:t('htmlReadingUi.analysisTime')} as Record<string,string>)[field]??field} · {(bytes/1024/1024).toFixed(2)} MB</p>)}<Button variant="link" size="sm" onClick={()=>setSection('channels')}>{t('htmlReadingUi.adjustChannelCountsAndContent')}</Button></details>}
    {c.preview&&<div className="space-y-2 rounded-md border p-3"><p className="text-sm">{t('htmlReadingUi.generatedHtml')}{c.preview.uniqueCount??c.preview.count} {t('htmlReadingUi.uniqueProjects')}{c.preview.count} {t('htmlReadingUi.channelEditionEntries')}{(c.preview.bytes/1024/1024).toFixed(2)} MB</p><p className="text-xs text-muted-foreground">{t('htmlReadingUi.marksInTheSeparatePreviewAreIsolated')}{window.electronAPI?.htmlReading?.preview?t('htmlReadingUi.desktopPreviewUsesASeparateWindowReopen'):t('htmlReadingUi.openASeparateBrowserPreviewIfPopups')}</p><div className="flex flex-wrap gap-2">{window.electronAPI?.htmlReading?.preview?<Button variant="outline" onClick={()=>void reopenPreview()}>{t('htmlReadingUi.reopenSeparatePreview')}</Button>:<Button variant="outline" onClick={()=>openReadingBrowserPreview(c.preview!.html)}>{t('htmlReadingUi.openSeparateBrowserPreview')}</Button>}<Button variant="outline" onClick={()=>downloadReadingPreview(c.preview!.html)}>{t('htmlReadingUi.downloadCurrentPreviewHtml')}</Button><Button variant="ghost" onClick={()=>{c.setPreview(null);setPreviewOpenError('');}}>{t('htmlReadingUi.closePreviewInformation')}</Button></div>{previewOpenError&&<p role="alert" className="text-sm text-destructive">{previewOpenError}</p>}<p className="text-xs text-muted-foreground">{t('htmlReadingUi.theDownloadButtonRequestsABrowserSave')}</p></div>}
    <div className="flex flex-wrap gap-2" role="tablist" aria-label={t('settingsUx.readingOptions')}>
      {[['overview',t('htmlReadingUi.overview')],['content',t('htmlReadingUi.contentScope')],['channels',t('htmlReadingUi.channelConfiguration')],['layout',t('htmlReadingUi.readingStyle')],['mail',t('htmlReadingUi.emailDelivery')],['records',t('htmlReadingUi.readingRecords')],['storage',t('htmlReadingUi.storageAndCleanup')]].map(([id,label]) => <Button key={id} variant={section === id ? 'secondary' : 'ghost'} size="sm" role="tab" id={`reading-tab-${id}`} aria-selected={section === id} aria-controls={`reading-panel-${id}`} onClick={() => setSection(id)}>{label}</Button>)}
    </div>
    <div role="tabpanel" id="reading-panel-overview" aria-labelledby="reading-tab-overview" hidden={section !== 'overview'} className="space-y-4">
      <ReadingGroup title={t('htmlReadingUi.currentReadingConfiguration')} description={t('htmlReadingUi.theOverviewShowsThisFormScheduledEmail')}>
        <dl className="grid gap-3 text-sm sm:grid-cols-2"><div><dt className="text-muted-foreground">{t('htmlReadingUi.contentScope')}</dt><dd>{s.repositories?t('htmlReadingUi.starredRepositoriesAtMostItems', { v1: s.categoryIds.length?t('htmlReadingUi.categories', { v1: s.categoryIds.length }):t('htmlReadingUi.allCategories'), v2: s.repositoryLimit }):t('htmlReadingUi.starredRepositoriesDisabled')}</dd></div><div><dt className="text-muted-foreground">{t('htmlReadingUi.discoveryChannels')}</dt><dd>{s.discovery?t('htmlReadingUi.selectedChannelsDefaultItemsPerChannelEdition', { v1: s.channelIds.length, v2: s.perChannel, v3: s.historyDays }):t('htmlReadingUi.discoveryDisabled')}</dd></div><div><dt className="text-muted-foreground">{t('htmlReadingUi.emailStatus')}</dt><dd>{credential?`${credential.from} → ${credential.to}`:t('htmlReadingUi.emailNotConfiguredForThisAccount')}</dd></div><div><dt className="text-muted-foreground">{t('htmlReadingUi.nextSavedSchedule')}</dt><dd>{c.saved.scheduleEnabled?nextBeijingSchedule(c.saved.sendTime,t):t('htmlReadingUi.dailyDeliveryDisabled')}{c.saved.scheduleEnabled&&!credential?t('htmlReadingUi.awaitingEmailCredential'):''}</dd></div><div><dt className="text-muted-foreground">{t('htmlReadingUi.managedAttachments')}</dt><dd>{c.mail.storage?t('htmlReadingUi.filesMb', { v1: c.mail.storage.files, v2: (c.mail.storage.bytes/1024/1024).toFixed(2) }):t('htmlReadingUi.desktopStorageStatisticsUnavailable')}</dd></div><div><dt className="text-muted-foreground">{t('htmlReadingUi.saveStatus')}</dt><dd>{dirty?t('htmlReadingUi.thisFormHasUnsavedChanges'):t('htmlReadingUi.thisFormMatchesSavedConfiguration')}</dd></div></dl>
        <p className="text-xs text-muted-foreground">{t('htmlReadingUi.theScheduledTimeStartsGenerationDeliveryWaits')}</p>
        <div className="flex flex-wrap gap-2"><Button variant="outline" onClick={()=>setSection('content')}>{t('htmlReadingUi.adjustContentScope')}</Button><Button variant="outline" onClick={()=>setSection('channels')}>{t('htmlReadingUi.adjustChannels')}</Button><Button variant="outline" onClick={()=>setSection('mail')}>{t('htmlReadingUi.viewEmailStatus')}</Button></div>
      </ReadingGroup>
      <ReadingGroup title={t('htmlReadingUi.currentIssues')}>{issues.length?issues.map((issue,index)=><p key={index} className="text-sm">{issue}</p>):<p className="text-sm text-muted-foreground">{t('htmlReadingUi.noConfigurationOrDeliveryIssuesCurrentlyNeed')}</p>}{c.reportStale&&<p className="text-sm">{t('htmlReadingUi.thePreviousContentCheckIsOutdatedPreview')}</p>}</ReadingGroup>
    </div>
    <div role="tabpanel" id="reading-panel-content" aria-labelledby="reading-tab-content" hidden={section !== 'content'} className="space-y-4">
    <ReadingGroup title={t('htmlReadingUi.readingPreset')} description={t('htmlReadingUi.thePresetControlsDefaultExpandedContentWithout')}>
      <ReadingSelect label={t('htmlReadingUi.readingPreset')} value={s.preset} options={[["browse",t('htmlReadingUi.browseCompleteSummariesUsageAndMaintenanceCollapsed')],["deep",t('htmlReadingUi.deepReadingCompleteSummariesAnalysisSectionsExpanded')]]} onChange={value=>{if(Object.keys(s.defaultProfile).length||Object.keys(s.repositoryProfile).length||Object.keys(s.discoveryProfile).length||Object.keys(s.channelProfiles).length)setPendingPreset(value as 'browse'|'deep');else set(v=>({...v,preset:value as 'browse'|'deep'}));}}/>
      {pendingPreset&&<div className="space-y-2 rounded border p-3"><p className="text-sm">{t('htmlReadingUi.customContentSettingsExistHowShouldSwitching')}</p><div className="flex flex-wrap gap-2"><Button onClick={()=>{set(v=>({...v,preset:pendingPreset}));setPendingPreset(null);}}>{t('htmlReadingUi.keepAdvancedOverrides')}</Button><Button variant="outline" onClick={()=>{set(v=>resetReadingPresentation(v,pendingPreset));setPendingPreset(null);}}>{t('htmlReadingUi.resetAdvancedOverridesAndSwitch')}</Button><Button variant="ghost" onClick={()=>setPendingPreset(null)}>{t('htmlReadingUi.cancel')}</Button></div></div>}
    </ReadingGroup>
    <ReadingGroup title={t('htmlReadingUi.pagesAndRepositoryScope')}>
      <label className="block space-y-2 text-sm"><span>{t('htmlReadingUi.htmlTitle')}</span><Input maxLength={80} value={s.title} onChange={e=>set(v=>({...v,title:e.target.value}))}/></label>
      <div className="grid gap-2 sm:grid-cols-2"><ReadingToggle label={t('htmlReadingUi.includeStarredRepositories')} checked={s.repositories} onChange={value=>set(v=>({...v,repositories:value}))}/><ReadingToggle label={t('htmlReadingUi.includeDiscovery')} checked={s.discovery} onChange={value=>set(v=>({...v,discovery:value}))}/></div>
      {s.repositories&&<><p className="text-sm font-medium">{t('htmlReadingUi.repositoryCategoryScope')}</p><p className="text-xs text-muted-foreground">{t('htmlReadingUi.noCategorySelectionIncludesAllRepositoriesSelected')}</p><div className="grid max-h-60 gap-2 overflow-auto sm:grid-cols-2">{[...c.catalog.categories,{id:'none',name:t('htmlReadingUi.uncategorized')}].map(cat=><ReadingToggle key={cat.id} label={cat.name} checked={s.categoryIds.includes(cat.id)} onChange={value=>select('categoryIds',cat.id,value)}/>)}</div><div className="grid gap-4 sm:grid-cols-2"><ReadingNumber label={t('htmlReadingUi.repositoryCountLimit')} value={s.repositoryLimit} min={1} max={10000} onChange={value=>set(v=>({...v,repositoryLimit:value}))}/><ReadingSelect label={t('htmlReadingUi.defaultRepositorySort')} value={s.repositorySort} options={[["stars",t('htmlReadingUi.starCount')],["updated",t('htmlReadingUi.recentlyUpdated')],["name",t('htmlReadingUi.projectName')]]} onChange={value=>set(v=>({...v,repositorySort:value as typeof s.repositorySort}))}/></div></>}
      <div className="grid gap-2 sm:grid-cols-2"><ReadingToggle label={t('htmlReadingUi.exportUnreadProjectsOnly')} checked={s.unreadOnly} onChange={value=>set(v=>({...v,unreadOnly:value}))}/><ReadingToggle label={t('htmlReadingUi.hideIgnoredProjects')} checked={s.hideIgnored} onChange={value=>set(v=>({...v,hideIgnored:value}))}/></div>
    </ReadingGroup>
    <ReadingAdvanced title={t('htmlReadingUi.advancedRepositoryContent')}><HtmlReadingProfile title={t('htmlReadingUi.repositoryContent')} inherited={resolveReadingProfile({...s,repositoryProfile:{}},'repositories')} override={s.repositoryProfile} onChange={value=>set(v=>({...v,repositoryProfile:value}))}/></ReadingAdvanced>
    </div>
    <div role="tabpanel" id="reading-panel-channels" aria-labelledby="reading-tab-channels" hidden={section !== 'channels'} className="space-y-4">
    {!s.discovery&&<p className="text-sm text-muted-foreground">{t('htmlReadingUi.theDiscoveryPageIsDisabledEnableIt')}</p>}
    {s.discovery&&<ReadingGroup title={t('htmlReadingUi.discoveryChannelsAndHistory')} description={t('htmlReadingUi.selectChannelsForTheFinalFileExports')}>
      <div className="grid gap-2 sm:grid-cols-2">{c.catalog.channels.map(channel=><ReadingToggle key={channel.id} label={channel.name} checked={s.channelIds.includes(channel.id)} onChange={value=>select('channelIds',channel.id,value)}/>)}</div>
      <div className="grid gap-4 sm:grid-cols-2"><ReadingNumber label={t('htmlReadingUi.itemLimitPerBuiltInChannelEdition')} value={s.perChannel} min={1} max={500} onChange={value=>set(v=>({...v,perChannel:value}))}/><ReadingNumber label={t('htmlReadingUi.maximumAgeOfReusableBuiltInChannel')} value={s.maxCacheAgeDays} min={1} max={7} onChange={value=>set(v=>({...v,maxCacheAgeDays:value}))}/><ReadingNumber label={t('htmlReadingUi.customEditionHistoryInDays')} value={s.historyDays} min={1} max={90} onChange={value=>set(v=>({...v,historyDays:value}))}/></div><p className="text-xs text-muted-foreground">{t('htmlReadingUi.previewAndExportAutomaticallyPrepareUnloadedBuilt')}</p><Button variant="outline" disabled={c.busy} onClick={()=>c.generate('preview',true)}>{t('htmlReadingUi.refreshChannelsAndPreview')}</Button><p className="text-xs text-muted-foreground">{t('htmlReadingUi.useThisForFreshResultsRefreshIs')}</p>
    </ReadingGroup>}
    {s.discovery&&<ReadingAdvanced title={t('htmlReadingUi.discoveryDefaultsAndAdvancedChannelOverrides')}><HtmlReadingProfile title={t('htmlReadingUi.defaultDiscoveryContent')} quantity inherited={resolveReadingProfile({...s,discoveryProfile:{},channelProfiles:{}},'discovery')} override={s.discoveryProfile} onChange={value=>set(v=>({...v,discoveryProfile:value}))}/>
      {s.channelIds.map((id,index)=>{const channel=c.catalog.channels.find(channel=>channel.id===id);if(!channel)return null;return <ReadingAdvanced key={id} title={`${channel.name} · ${Object.keys(s.channelProfiles[id]??{}).length?t('htmlReadingUi.overridden'):t('htmlReadingUi.inheritsDiscoveryDefaults')}`}><div className="my-2 flex gap-2"><Button size="sm" variant="outline" disabled={index===0} onClick={()=>set(v=>{const ids=[...v.channelIds];[ids[index-1],ids[index]]=[ids[index],ids[index-1]];return {...v,channelIds:ids};})}>{t('htmlReadingUi.moveChannelUp')}</Button><Button size="sm" variant="outline" disabled={index===s.channelIds.length-1} onClick={()=>set(v=>{const ids=[...v.channelIds];[ids[index+1],ids[index]]=[ids[index],ids[index+1]];return {...v,channelIds:ids};})}>{t('htmlReadingUi.moveChannelDown')}</Button></div><HtmlReadingProfile title={channel.name} quantity inherited={resolveReadingProfile({...s,channelProfiles:{}},id)} override={s.channelProfiles[id]??{}} onChange={value=>set(v=>{const profiles={...v.channelProfiles};if(Object.keys(value).length)profiles[id]=value;else delete profiles[id];return {...v,channelProfiles:profiles};})}/></ReadingAdvanced>;})}
    </ReadingAdvanced>}
    </div>
    <div role="tabpanel" id="reading-panel-layout" aria-labelledby="reading-tab-layout" hidden={section !== 'layout'} className="space-y-4">
    <HtmlReadingProfile title={t('htmlReadingUi.globalContentDefaults')} inherited={resolveReadingProfile({...s,defaultProfile:{},repositoryProfile:{},discoveryProfile:{},channelProfiles:{}},'repositories')} override={s.defaultProfile} onChange={value=>set(v=>({...v,defaultProfile:value}))}/>
    <p className="text-xs text-muted-foreground">{t('htmlReadingUi.existingNotesAreOmittedByDefaultDisabling')}</p>
    <ReadingGroup title={t('htmlReadingUi.readingStyleAndFileSize')}><div className="grid gap-4 sm:grid-cols-2">
      <ReadingSelect label={t('htmlReadingUi.defaultPage')} value={s.initialPage} options={[["repositories",t('htmlReadingUi.repositories')],["discovery",t('htmlReadingUi.discovery')]]} onChange={value=>set(v=>({...v,initialPage:value as typeof s.initialPage}))}/>
      <ReadingSelect label={t('htmlReadingUi.defaultColorMode')} value={s.theme} options={[["desktop",t('htmlReadingUi.desktopAppearanceAtGenerationTime')],["system",t('htmlReadingUi.phoneSystemAppearance')],["light",t('htmlReadingUi.light')],["dark",t('htmlReadingUi.dark')]]} onChange={value=>set(v=>({...v,theme:value as typeof s.theme}))}/>
      <ReadingSelect label={t('htmlReadingUi.bodyFontSize')} value={s.fontSize} options={['14','16','18','20'].map(size=>[size,`${size}px`])} onChange={value=>set(v=>({...v,fontSize:value as typeof s.fontSize}))}/>
      <ReadingSelect label={t('htmlReadingUi.cardDensity')} value={s.density} options={[["compact",t('htmlReadingUi.compact')],["standard",t('htmlReadingUi.standard')]]} onChange={value=>set(v=>({...v,density:value as typeof s.density}))}/>

      <ReadingNumber label={t('htmlReadingUi.htmlFileSizeLimitMb')} value={s.maxFileMb} min={1} max={15} onChange={value=>set(v=>({...v,maxFileMb:value}))}/>
    </div><p className="text-xs text-muted-foreground">{t('htmlReadingUi.inheritsDesktopThemeAccentColorAndCorner')}</p></ReadingGroup>
    <ReadingGroup title={t('htmlReadingUi.whatCanBeChangedOnThePhone')} description={t('htmlReadingUi.onlyTheseOperationsAreExportedManualCategories')}><ReadingToggle label={t('htmlReadingUi.automaticallyMarkReadWhenOpeningDetails')} checked={s.autoRead} onChange={value=>set(v=>({...v,autoRead:value}))}/><ReadingFlags labels={operationLabels} values={s.operations} onChange={(key,value)=>set(v=>({...v,operations:{...v.operations,[key]:value}}))}/></ReadingGroup>
    </div>
    <div role="tabpanel" id="reading-panel-mail" aria-labelledby="reading-tab-mail" hidden={section !== 'mail'}><HtmlReadingMail controller={c}/></div>
    <div role="tabpanel" id="reading-panel-records" aria-labelledby="reading-tab-records" hidden={section !== 'records'} className="space-y-4"><HtmlReadingImport controller={c}/></div>
    <div role="tabpanel" id="reading-panel-storage" aria-labelledby="reading-tab-storage" hidden={section !== 'storage'} className="space-y-4">
      <ReadingGroup title={t('htmlReadingUi.managedAttachmentsAndCleanup')} description={t('htmlReadingUi.cleanupDeletesOnlyExpiredManagedHtmlAttachments')}>
        <p className="text-sm">{c.mail.storage?t('htmlReadingUi.attachmentsMbCurrentRetentionDays', { v1: c.mail.storage.files, v2: (c.mail.storage.bytes/1024/1024).toFixed(2), v3: c.mail.storage.retentionDays }):t('htmlReadingUi.attachmentStorageStatisticsAreUnavailableInThis')}</p>
        <ReadingNumber label={t('htmlReadingUi.managedAttachmentRetentionInDays')} value={s.artifactRetentionDays} min={7} max={365} onChange={value=>set(v=>({...v,artifactRetentionDays:value}))}/>
        <p className="text-xs text-muted-foreground">{t('htmlReadingUi.defaultsToDaysAndTakesEffectAfter')}</p>
        <Button variant="outline" disabled={c.busy||!window.electronAPI?.htmlReading?.cleanup} onClick={c.cleanup}>{t('htmlReadingUi.cleanExpiredAttachments')}</Button>
      </ReadingGroup>
      <ReadingGroup title={t('htmlReadingUi.builtInDiscoveryChannelCache')}><p className="text-sm">{c.cacheStats?t('htmlReadingUi.cachedEntriesMb', { v1: c.cacheStats.entries, v2: (c.cacheStats.bytes/1024/1024).toFixed(2) }):t('htmlReadingUi.loadingCacheStatisticsForThisAccount')}</p><p className="text-xs text-muted-foreground">{t('htmlReadingUi.afterClearingTheNextGenerationNeedsNetwork')}</p><Button variant="outline" disabled={c.busy||!c.cacheStats?.entries} onClick={c.clearCache}>{t('htmlReadingUi.clearThisAccountSBuiltInChannel')}</Button></ReadingGroup>
      <ReadingGroup title={t('htmlReadingUi.readingData')}><p className="text-sm">{Object.keys(c.data?.states??{}).length} {t('htmlReadingUi.projectReadingRecords')}{Object.values(c.data?.states??{}).filter(state=>state.candidate).length} {t('htmlReadingUi.candidates')}</p><p className="text-xs text-muted-foreground">{t('htmlReadingUi.filesDownloadedElsewhereAreManagedByYou')}</p></ReadingGroup>
    </div>
  </div>;
}
